---

- name: Create a qrouter - qrouter-create.sh
  script: qrouter-create.sh {{ BRIDGE_NAME }} {{ NET_NAME }} {{ SUBNET_NAME }} {{ ROUTER_NAME }} {{ SITE_CIDR }} {{ SITE_GATEWAY }}
  environment: os_env
  when: subcommand == 'qrouter_create'
  register: qrouter_create

- name: Destroy a qrouter - qrouter-destroy.sh
  script: qrouter-destroy.sh {{ BRIDGE_NAME }} {{ NET_NAME }} {{ SUBNET_NAME }} {{ ROUTER_NAME }}
  environment: os_env
  when: subcommand == 'qrouter_destroy'
  ignore_errors: yes
  register: qrouter_destroy

- debug: var=qrouter_create.stdout_lines
- debug: var=qrouter_destroy.stdout_lines

