---
- name: Add network emulation - netem-add.sh
  script: netem-add.sh {{ BRIDGE_NAME }} {{ ROUTER_NAME }} {{ REMOTE_CIDR }} {{ DELAY }} {{ RATE }} {{ CEIL }}
  environment: os_env
  when: subcommand == 'netem_add'
  register: netem_add

- name: Delete network emulation - netem-del.sh
  script: netem-del.sh {{ BRIDGE_NAME }} {{ ROUTER_NAME }} {{ REMOTE_CIDR }}
  environment: os_env
  when: subcommand == 'netem_del'
  register: netem_del

- debug: var=netem_add.stdout_lines
- debug: var=netem_del.stdout_lines

