---
- name: Create an ovs port - tunnel-create.sh
  script: tunnel-create.sh {{ BRIDGE_NAME }} {{ TUNNEL_NAME }} {{ REMOTE_IP }}
  when: subcommand == 'tunnel_create'
  ignore_errors: yes
  register: tunnel_create

- name: Destroy an ovs port - tunnel-destroy.sh
  script: tunnel-destroy.sh {{ BRIDGE_NAME }} {{ TUNNEL_NAME }}
  when: subcommand == 'tunnel_destroy'
  ignore_errors: yes
  register: tunnel_destroy

- debug: var=tunnel_create.stdout_lines
- debug: var=tunnel_destroy.stdout_lines

