# Author: Hee Won Lee <knowpd@research.att.com>
# Created on Oct 1, 2015
---

- hosts: "{{ HOST }}" 
  remote_user: yourusername
  sudo: yes
  gather_facts: no
  
  roles:
    - {role: qrouter, subcommand: qrouter_create}
