---

- name: Initiaize a route - route-init.sh
  script: route-init.sh {{ BRIDGE_NAME }} {{ ROUTER_NAME }} {{ WANIP_PREFIXLEN }}
  environment: os_env
  when: subcommand == 'route_init'
  ignore_errors: yes
  register: route_init

- name: Add a route - route-add.sh
  script: route-add.sh {{ ROUTER_NAME }} {{ REMOTE_CIDR }} {{ REMOTE_GATEWAY }}
  environment: os_env
  when: subcommand == 'route_add'
  ignore_errors: yes
  register: route_add

- name: Delete a route - route-del.sh
  script: route-del.sh {{ ROUTER_NAME }} {{ REMOTE_CIDR }}
  environment: os_env
  when: subcommand == 'route_del'
  #ignore_errors: yes
  register: route_del

- debug: var=route_init.stdout_lines
- debug: var=route_add.stdout_lines
- debug: var=route_del.stdout_lines

